### ISSUE TITLE
Improve project infrastructure

### ISSUE THREAD

**Issue by CKGrafico** [CKGrafico/papanasi#50]
Stop working on components and create a long-term infrastructure.

To finish this we have also will include 

- [X] Improve CLI for compilation 
- [x] Choose state and styles for each framework
- [x] Improve local dev scripts (new cli??)
- [x] Separate logic from components + communication between components (signal?) #45
- [x] Think again about signals, not working as expected when more than once the same component
- [x] Improve all the components like avatar
- [x] Fix signals in solid https://github.com/preactjs/signals/issues/223
- [ ] Refactor Code component
- [x] check solid refs #42
- [x] check typings status #8
- [x] add alias on imports #11
- [ ] Qwik #49 
- [x] Add all this information to the readmes
- [ ] Fix storybook errors

**Comment by CKGrafico** [comment]
New CLI:
![haw](https://user-images.githubusercontent.com/2048511/192138188-4444b62f-2555-46fc-8b7b-18868e24286e.gif)
